### PR TITLE
feat:  Accept CloudWatch streams OTLP output format to allow CloudWatch metrics ingestion

### PR DESCRIPTION
**Pull request by garlic-hub**
impl #3683

## Summary by CodeRabbit

- **New Features**
	- Enhanced data ingestion functionality with improved decoding for various data formats including JSON and Protobuf.
	- Added support for output formats in CloudWatch custom metric streams, allowing users to choose between JSON and OpenTelemetry 1.0.

- **Bug Fixes**
	- Improved error handling and flexibility in data ingestion processes.

- **Tests**
	- Expanded test suite to validate new decoding functions and ensure robustness in data handling.

### CODE REVIEW

**Comment by hengfeiyang** [comment]
@garlic-hub I have one question, this PR is for ingestion CloudWatch metrics by `OTLP` format, but i saw the code you are changing the `IngestionData::GCP`, should we change `IngestionData::KinesisFH`?

**Comment by garlic-hub** [comment]
@hengfeiyang `IngestionData::GCP` has not changed in functionality. The change you see there is `decode_and_decompress_to_string()` which is not a new function. I only renamed it because now there are two different functions that decode and decompress. One to `String` (JSON values) and one to `Vec<u8>` (possibly protobuf values). This change needed to happen because protobufs are not valid UTF-8, so you must test that they are protobufs before attempting to generate a Rust `String` from them.

**Comment by hengfeiyang** [comment]
@garlic-hub Sorry, i didn't check the code carefully, you are right.

**Comment by hengfeiyang** [comment]
@garlic-hub Have you tried ingestion with otlp protocol? we can help you on testing.

**Comment by garlic-hub** [comment]
> @garlic-hub Have you tried ingestion with otlp protocol? we can help you on testing.

I've tested this with both a JSON stream and an OTLP 1.0 stream. Both worked without issue, but I did not do any performance testing. I matched the schema of the values generated from the OTLP metrics to the schema of the values generated from JSON metrics as closely as possible.

**Review by taimingl — APPROVED** [review]

**Pull request merged**
