### PR TITLE
feat: dashboard report API

### LINKED ISSUE #2598: Sending dashboards daily (or other predefined interval) to specific emails
### Which OpenObserve functionalities are relevant/related to the feature request?

dashboards

### Description

OpenObserve is meant to capture and analyze observability data. A lot of the log data contains business-specific details as well. Executives might need this business data on a regular basis to make business decisions. 

Dashboards are a great way to expose this data to anyone. Having the ability to send the dashboard data as an email to the specified users can be extremely useful.

### Proposed solution

Provide a reporting functionality that allows to sending a particular dashboard at a specified time to specific destinations (emails).

image

### Alternatives considered

N/A

### PR DESCRIPTION
**Pull request by Subhra264**
Fixes #2598.

## Report APIs
```
POST /{org_id}/reports  -- Create Report
GET /{org_id}/reports/{name} -- Get One Report
GET /{org_id}/reports -- List of Reports
PUT /{org_id}/reports/{name} -- Update Report
DELETE /{org_id}/reports/{name} -- Delete Report
PUT /{org_id}/reports/{name}/enable?value=<true|false> -- Enable/disable
PUT /{org_id}/reports/{name}/trigger -- trigger report immediately
```

**Example Payload**
```
{
  "dashboards": [
    {
      "dashboard": "7169258435064627202",
      "folder": "default",
      "tabs": [
        "default"
      ],
      "timerange": {
        "from": 0,
        "period": "1M",
        "to": 0,
        "type": "relative"
      },
      "variables": []
    }
  ],
  "description": "Some description saying hello world",
  "message": "<p>Message for new report</p>",
  "destinations": [
    {
      "email": "hi@bye.com"
    }
  ],
  "enabled": true,
  "frequency": {
    "type": "once",
    "interval": 1
  },
  "mediaType": "pdf",
  "name": "new_final_report",
  "orgId": "default",
  "password": "",
  "start": 1709288798985384,
  "title": "Report name title",
  "user": ""
}
```

**Notes**
- For now, only "pdf" `mediaType` is supported.
- The frequency type have these possible values - `once` (triggered once at the given `start` time, interval is ignored), `hours` (`interval` value is treated as number of hours as interval), `days` (`interval` value is treated as number of days as interval), `weeks` (`interval` value is treated as number of weeks as interval), `months` (`interval` value is treated as number of months as interval and each month is assumed to be of fixed 30 days).
- Only email destination is supported for now.
- Even though `dashboards` and `tabs` are arrays, only the first element is used to generate report, i.e. one report can be generated only for one dashboard tab for now.
- `variables` are ignored for now.
- `start` is start date converted to timezone-independent UNIX microseconds.
- `wait_for_navigation` and `find_element` provided by `chromiumoxide` does not really wait for elements to be loaded. So, the code uses `tokio::time::sleep` to wait for certain seconds to let the dashboard load. The `ZO_CHROME_SLEEP_SECS` env can be set to set the sleep time in secs and defaults to 20 seconds.
- **Requires `ZO_CHROME_ENABLED` and `ZO_SMTP_ENABLED` to be `true` and all necessary SMTP configs must be set properly. See https://github.com/openobserve/openobserve/pull/2810.**
- `ZO_CHROME_PATH` can be optionally set to the path where chromium is located. If not specified, it looks for chrome executable in default locations (like `CHROME` env, user path, registry in case of windows etc.) and if not found, it downloads a good known version of chromium at the path specified by `ZO_CHROME_DOWNLOAD_PATH` (default is `download` folder in the project root directory).

### CODE REVIEW

**Review by omkarK06 — APPROVED** [review]

**Comment by gaby** [comment]
@hengfeiyang Why was this close? Sounds like a very useful feature!

**Comment by hengfeiyang** [comment]
already merged the feature, close this because we changed main branch from `dev` to `main`.

**Comment by gaby** [comment]
I don't remember seeing it in the API page, unless its an enterprise feature

**Comment by hengfeiyang** [comment]
here: https://github.com/openobserve/openobserve/blob/main/src/handler/http/request/dashboards/reports.rs

**Pull request closed without merging**
