### PR TITLE
feat: add support for aws s3 client retry

### LINKED ISSUE #4411: Add possibility to tweak maximum number of retries for AWS S3 client
### Which OpenObserve functionalities are relevant/related to the feature request?

other

### Description

During some compaction cycles, we often see this error message:
```
Generic S3 error: Error after 1 retries in 3.848121029s, max_retries:10, retry_timeout:180s, source:error sending request for url (https://s3.us-east-1.amazonaws.com/XXXXX)
```
It only retries 1 or 2 times and then the error gets resolved. From what I saw in the arrow-rs repository, the full error source would be printed only when we reach maximum retries.
Since we don't hit the maximum retries we can't have an idea of what's happening. 
Therefore, we want to have an option to tweak the maximum number of retries to help us in the troubleshooting process.

### Proposed solution

- Add a new environment variable probably named `AWS_S3_MAX_RETRIES`
- Add a backoff configuration for the AWS S3 Client with the configured environment variables
- Incorporate the change in Helm chart 

### Alternatives considered

N/A

### PR DESCRIPTION
**Pull request by TessaIO**
Resolves #4411 

## Summary by CodeRabbit

- **New Features**
	- Added a configurable maximum retry option for AWS S3 operations, allowing users to specify the number of retries for enhanced error handling.
- **Improvements**
	- Enhanced the AWS S3 client to better manage retries during operations, improving resilience in the event of network failures.

### CODE REVIEW

**Review by hengfeiyang — APPROVED** [review]

**Comment by TessaIO** [comment]
@hengfeiyang I updated the branch can you check?

**Comment by hengfeiyang** [comment]
@TessaIO there is an error of CI, we need to fix it
image

**Comment by TessaIO** [comment]
@hengfeiyang removed that line can u check again please?

**Comment by hengfeiyang** [comment]
@TessaIO Thank you for that, merged.

**Pull request merged**
