### PR TITLE
fix: all labels to have string values 

### PR DESCRIPTION
**Pull request by oasisk**
- [x] As part of OTLP ingestion, some labels like "is_monotonic" were having non-string values , which was creating issue for promql query ,fixed these to have to string value
- [x] Metric names were invalid , containing "." , "-" etc , fixed these to have only a-zA-Z0-9_: 
- [x] Labels to have only a-zA-Z0-9_

### CODE REVIEW

**Review by hengfeiyang — APPROVED** [review]

**Comment by trdmm** [comment]
How to migrate data from old streams to new steams?

**Comment by hengfeiyang** [comment]
@trdmm What is your problem?

**Comment by trdmm** [comment]
> @trdmm What is your problem?

My old steam name is `iov-tcp`, when I upgrade from `0.5.2` to `0.6.4`, it add a new stream `iov_tcp`.
So part of the data is in `iov-tcp` steam, and the other part of the data is in `iov_tcp` stream. It is not convenient to query logs.

**Comment by hengfeiyang** [comment]
Which type are you using single node with local disk or cluster with s3?

**Comment by trdmm** [comment]
> Which type are you using single node with local disk or cluster with s3?

local disk

**Comment by hengfeiyang** [comment]
@trdmm You can follow the steps:

1. stop OpenObserve
2. copy the files in `data/streams/default/logs/iov-tcp` into `data/streams/default/logs/iov_tcp`
3. Open the database `data/db/metadata.sqlite` and run `UPDATE file_list SET stream='default/logs/iov_tcp' WHERE stream='default/logs/iov-tcp;`
4. Start OpenObserve

Now, you can search the old data from `iov_tcp`, after you confirm that, you can delete the old stream `iov-tcp` from `streams` page.

**Comment by trdmm** [comment]
> @trdmm You can follow the steps:
> 
> 1. stop OpenObserve
> 2. copy the files in `data/streams/default/logs/iov-tcp` into `data/streams/default/logs/iov_tcp`
> 3. Open the database `data/db/metadata.sqlite` and run `UPDATE file_list SET stream='default/logs/iov_tcp' WHERE stream='default/logs/iov-tcp;`
> 4. Start OpenObserve
> 
> Now, you can search the old data from `iov_tcp`, after you confirm that, you can delete the old stream `iov-tcp` from `streams` page.

Perfect solution to the problem 😄 .
Although there is a semicolon missing at the end of step 3 🤪 .

**Pull request merged**
