### PR TITLE
fix: run the mmdb downloader everywhere

### PR DESCRIPTION
**Pull request by ansrivas**
- mmdb-downloader wasn't enabled on ingestor, enabled that.
- mmdb-client wasn't initialized on the first run ( in case the file
  already existed ), so enabled that

### CODE REVIEW

**Comment by gaby** [comment]
@prabhatsharma I think this will fail if the OpenObserve instance doesnt have internet access. This should be optional via ENV variable

**Comment by prabhatsharma** [comment]
> @prabhatsharma I think this will fail if the OpenObserve instance doesnt have internet access. This should be optional via ENV variable

It's guarded by `ZO_MMDB_DISABLE_DOWNLOAD` with `false` as default. Should be fine. Download will just fail if the internet connection is not available. No major downside - just a warning in console. Setting the value to `true` by default will lead to more work by the users who might need it and may require for them to first find the relevant configuration to enable it.

Default behavior should be sane enough that most users who need the functionality should be able to get it by putting no extra effort.

**Comment by gaby** [comment]
> > @prabhatsharma I think this will fail if the OpenObserve instance doesnt have internet access. This should be optional via ENV variable
> 
> It's guarded by `ZO_MMDB_DISABLE_DOWNLOAD` with `false` as default. Should be fine. Download will just fail if the internet connection is not available. No major downside - just a warning in console. Setting the value to `true` by default will lead to more work by the users who might need it and may require for them to first find the relevant configuration to enable it.
> 
> Default behavior should be sane enough that most users who need the functionality should be able to get it by putting no extra effort.

Thanks that should cover it. Probably worth adding that ENV to the docs here: https://openobserve.ai/docs/environment-variables/#common

**Comment by prabhatsharma** [comment]
Yeah, the whole section on front end monitoring needs to be added to documentation.

> > > @prabhatsharma I think this will fail if the OpenObserve instance doesnt have internet access. This should be optional via ENV variable
> > 
> > 
> > It's guarded by `ZO_MMDB_DISABLE_DOWNLOAD` with `false` as default. Should be fine. Download will just fail if the internet connection is not available. No major downside - just a warning in console. Setting the value to `true` by default will lead to more work by the users who might need it and may require for them to first find the relevant configuration to enable it.
> > Default behavior should be sane enough that most users who need the functionality should be able to get it by putting no extra effort.
> 
> Thanks that should cover it. Probably worth adding that ENV to the docs here: https://openobserve.ai/docs/environment-variables/#common

Yes, we have the whole section on front end monitoring waiting to be written. We will cover it as part of that.

**Comment by gaby** [comment]
> Yeah, the whole section on front end monitoring needs to be added to documentation.
> 
> > > > @prabhatsharma I think this will fail if the OpenObserve instance doesnt have internet access. This should be optional via ENV variable
> > > 
> > > 
> > > It's guarded by `ZO_MMDB_DISABLE_DOWNLOAD` with `false` as default. Should be fine. Download will just fail if the internet connection is not available. No major downside - just a warning in console. Setting the value to `true` by default will lead to more work by the users who might need it and may require for them to first find the relevant configuration to enable it.
> > > Default behavior should be sane enough that most users who need the functionality should be able to get it by putting no extra effort.
> > 
> > 
> > Thanks that should cover it. Probably worth adding that ENV to the docs here: https://openobserve.ai/docs/environment-variables/#common
> 
> Yes, we have the whole section on front end monitoring waiting to be written. We will cover it as part of that.

Thanks! 💪

**Review by hengfeiyang — APPROVED** [review]

**Pull request merged**
