### PR TITLE
feat: color palette for dashboard chart

### PR DESCRIPTION
**Pull request by ktx-abhay**
- Color palette for dashboard chart.
- By default, `Palette-Classic (By Series)` will be selected.
image

### CODE REVIEW

**Comment by gaby** [comment]
@ktx-abhay This looks awesome! Can't wait for this feature. It would make charts even more usefull

**Comment by gaby** [comment]
@ktx-abhay Any updates on this feature?

**Comment by ktx-abhay** [comment]
@gaby facing issue while finding unique color based on unique series name. Currently, there is an chance of getting same color for different series name.

**Comment by Ignaciojeria** [comment]
that looks interesting :D

**Comment by ktx-abhay** [comment]
Refer #4774

**Pull request closed without merging**
