### PR TITLE
feat: Add colored chips to logs columns

### PR DESCRIPTION
**Pull request by Kaboolean**
This feature adds more configuration to tables in dashboard panels, allowing to colorize any props.value by column name, depending on values contained or equal to.

image

image

image

### CODE REVIEW

**Comment by gaby** [comment]
This fixes https://github.com/openobserve/openobserve/issues/3398

Why is called "Chip" though? Any way of adding an option to color the whole column?

**Comment by Kaboolean** [comment]
> This fixes #3398
> 
> Why is called "Chip" though? Any way of adding an option to color the whole column?

Chip for something "round", maybe it isn't relevant. Maybe "Dot" would fit more.

**Comment by gaby** [comment]
> > This fixes #3398
> > Why is called "Chip" though? Any way of adding an option to color the whole column?
> 
> Chip for something "round", maybe it isn't relevant. Maybe "Dot" would fit more.

It should be `Color Scheme`, like Grafana does.

See here https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/table/

**Comment by Kaboolean** [comment]
> > > This fixes #3398
> > > Why is called "Chip" though? Any way of adding an option to color the whole column?
> > 
> > 
> > Chip for something "round", maybe it isn't relevant. Maybe "Dot" would fit more.
> 
> It should be `Color Scheme`, like Grafana does.
> 
> See here https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/table/

We don't change the color of the column or the cell but just fasten the table reading with a chip.

**Comment by ktx-kirtan** [comment]
@Kaboolean Thank you so much for the contribution. But we have already planned for this and it is in progress. Where we will have options to color code cells and rows based on some specific conditions.

**Comment by hengfeiyang** [comment]
@Kaboolean Thank you very much, but this feature is already in progressing, i will close it. if you want to contribute something else, maybe we can confirm it before you start.

**Comment by ktx-abhay** [comment]
- Refer #4596

**Pull request closed without merging**
